language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
sudo: true

before_install: "sudo apt-get install python-dev libevent-dev"

# command to install dependencies
#install: pip install nose gevent>=1.1rc5; python setup.py install

# command to run tests
#script: nosetests
script: py.test
