language: python
python:
  - "2.6"
  - "2.7"

before_install: "sudo apt-get install python-dev libevent-dev"

# command to install dependencies
install: python setup.py install

# command to run tests
script: python setup.py test
